### ISSUE TITLE
[Story] Users should be able to ..

### ISSUE THREAD

**Issue by ionutb-kyndryl** [ionutb-kyndryl/ionutb-kyndryl#4]
# Description
users is not able to click on some stuff

# What we want to achieve
Make use be abel to choose whatever tgey wan to 

#Tasks
- [x] #5
- [x] Make necesary code change
- [x] Create a automated test
- [x] Push to dev
- [x] Do test in UAT
- [x] Move ro PROD
